packages:
  - .

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

overrides:
  tailwindcss>nanoid: 3.3.7
  nanoid: 5.1.16
  lodash: 4.18.0
  lodash-es: 4.18.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
